<!DOCTYPE especie [
        <!ELEMENT especie (nombre, familia, distribucion)>
        <!ATTLIST especie estado (extinto | amenazado | sin-peligro) #REQUIRED>

        <!ELEMENT nombre (#PCDATA)>
        <!ATTLIST nombre nombre-cientifico CDATA #REQUIRED>

        <!ELEMENT familia (#PCDATA)>

        <!ELEMENT distribucion (zona+)>
        <!ELEMENT zona (#PCDATA)>
        ]>

<especie estado="amenazado">
    <nombre nombre-cientifico="Monachus monachus">Foca monje</nombre>
    <familia>Phocidae</familia>
    <distribucion>
        <zona>Costa Atlántica</zona>
        <zona>Costa Mediterránea</zona>
    </distribucion>
</especie>
